baseURL = "https://metabiolab.github.io/IFA736"
title = "IFA736 - Tópicos em Biofísica"
theme = "hugo-geekdoc"

pluralizeListTitles = false

uglyURLs = true
relativeURLs = true

# Geekdoc required configuration
pygmentsUseClasses = true
pygmentsCodeFences = true
disablePathToLower = true

# Required if you want to render robots.txt template
enableRobotsTXT = true

# Needed for mermaid shortcodes
[markup]
  [markup.goldmark.renderer]
    # Needed for mermaid shortcode
    unsafe = true
  [markup.tableOfContents]
    startLevel = 1
    endLevel = 9

[taxonomies]
   tag = "tags"